import Sidebar from "@/components/shared/Sidebar";
import type { Metadata } from "next";

export const metadata: Metadata = {
	title: "Rittika Dev Portfolio Dashboard",
	description: "Generated by create next app",
};

export default function DashboardLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<div className="min-h-screen my-2">
			<div className="flex justify-between">
				<div className="w-[15%] dark:bg-slate-800 bg-slate-200">
					<Sidebar />
				</div>
				<div className="w-[85%] dark:bg-darkTheme bg-lightTheme rounded-xl ml-2">
					{children}
				</div>
			</div>
		</div>
	);
}
